version: '3.8'

services:
  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Cybertech@123
      POSTGRES_DB: cybertech-postgres
    ports:
      - '5434:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data