version: "3.12"

services:
  be-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${HARBOR_URL}/${HARBOR_USERNAME}/${IMAGE}:${GITHUB_SHA}
    ports:
      - 4000:4000
    volumes:
      - /home/primetek/resource-web/cdn:/home/ubuntu/cdn