import 'dotenv/config';

const NODE_ENV = process.env.NODE_ENV ?? 'production';
const PORT = process.env.NODE_APP_PORT ?? '3000';
const HOST_NAME = process.env.NODE_APP_HOST_NAME ?? 'localhost';
const DB_HOSTNAME = process.env.NODE_APP_DB_HOSTNAME ?? 'localhost';
const DB_PORT = Number(process.env.NODE_APP_DB_PORT) ?? 5434;
const DB_TYPE = process.env.NODE_APP_DB_TYPE ?? 'postgres';
const DB_USERNAME = process.env.NODE_APP_DB_USERNAME ?? 'postgres';
const DB_PASSWORD = process.env.NODE_APP_DB_PASSWORD ?? '123123';
const DB_NAME = process.env.NODE_APP_DB_NAME ?? 'postgres';
const TYPEORM_SYNC = Boolean(process.env?.NODE_APP_TYPEORM_SYNC || false);
const JWT_SECRET = process.env.NODE_APP_JWT_SECRET ?? 'topSecret51';
const EXPIRES_IN = process.env.NODE_APP_EXPIRES_IN ?? 3600;
const SWAGGER = Boolean(process.env.NODE_APP_SWAGGER || false);

const APP_NAME = process.env.APP_NAME;
const APP_ENV = process.env.APP_ENV;
const APP_DEBUG = process.env.APP_DEBUG;
const APP_URL = process.env.APP_URL;
const APP_PORT = process.env.APP_PORT;
const APP_URL_PREFIX = process.env.APP_URL_PREFIX;
const LOG_CHANNEL = process.env.LOG_CHANNEL;
const DB_CONNECTION = process.env.DB_CONNECTION;
const DB_HOST = process.env.DB_HOST;
const DB_DATABASE = process.env.DB_DATABASE;
const TYPEORM_KEEPCONNECTIONALIVE = process.env.TYPEORM_KEEPCONNECTIONALIVE;
const TYPEORM_LOGGING = process.env.TYPEORM_LOGGING;
const TYPEORM_SYNCHRONIZE = process.env.TYPEORM_SYNCHRONIZE;
const TYPEORM_UUID_EXTENSION = process.env.TYPEORM_UUID_EXTENSION;
const BROADCAST_DRIVER = process.env.BROADCAST_DRIVER;
const CACHE_DRIVER = process.env.CACHE_DRIVER;
const QUEUE_CONNECTION = process.env.QUEUE_CONNECTION;
const SESSION_DRIVER = process.env.SESSION_DRIVER;
const SESSION_LIFETIME = process.env.SESSION_LIFETIME;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
const REDIS_PORT = process.env.REDIS_PORT;
const MAIL_MAILER = process.env.MAIL_MAILER;
const MAIL_HOST = process.env.MAIL_HOST;
const MAIL_PORT = process.env.MAIL_PORT;
const MAIL_USERNAME = process.env.MAIL_USERNAME;
const MAIL_PASSWORD = process.env.MAIL_PASSWORD;
const MAIL_ENCRYPTION = process.env.MAIL_ENCRYPTION;
const MAIL_SECURE = process.env.MAIL_SECURE;
const MAIL_FROM_ADDRESS = process.env.MAIL_FROM_ADDRESS;
const MAIL_FROM_NAME = process.env.MAIL_FROM_NAME;
const MAIL_TEMPLATE_DIR = process.env.MAIL_TEMPLATE_DIR;
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_DEFAULT_REGION = process.env.AWS_DEFAULT_REGION;
const AWS_BUCKET = process.env.AWS_BUCKET;
const PUSHER_APP_ID = process.env.PUSHER_APP_ID;
const PUSHER_APP_KEY = process.env.PUSHER_APP_KEY;
const PUSHER_APP_SECRET = process.env.PUSHER_APP_SECRET;
const PUSHER_APP_CLUSTER = process.env.PUSHER_APP_CLUSTER;
const MIX_PUSHER_APP_KEY = process.env.MIX_PUSHER_APP_KEY;
const MIX_PUSHER_APP_CLUSTER = process.env.MIX_PUSHER_APP_CLUSTER;
const USER_PASSWORD_BCRYPT_SALT_ROUNDS =
  process.env.USER_PASSWORD_BCRYPT_SALT_ROUNDS;
const JWT_SIGN_OPTIONS_ALGORITHM = process.env.JWT_SIGN_OPTIONS_ALGORITHM;
const JWT_SIGN_OPTIONS_EXPIRESIN = process.env.JWT_SIGN_OPTIONS_EXPIRESIN;
const SWAGGER_ENABLED = process.env.SWAGGER_ENABLED;
const SWAGGER_PATH = process.env.SWAGGER_PATH;
const IMAGE_PATH = process.env.IMAGE_PATH;
const IMAGE_API = process.env.IMAGE_API;
const IMAGE_FILE_SIZE = process.env.IMAGE_FILE_SIZE;
const PRODUCT_TEMPLATES_PATH = process.env.PRODUCT_TEMPLATES_PATH;
const BARCODE = process.env.BARCODE;
const TWILIO_NUMBER = process.env.TWILIO_NUMBER;
const TWILIO_SID = process.env.TWILIO_SID;
const TWILIO_AUTH = process.env.TWILIO_AUTH;
const PRINTER_API = process.env.PRINTER_API;
const UPLOAD_FILE_PATH = process.env.UPLOAD_FILE_PATH;
const UPLOAD_FILE_SIZE = process.env.UPLOAD_FILE_SIZE;
const EXPIRE_TIME = process.env.EXPIRE_TIME;
const EMAIL_SECURE = process.env.EMAIL_SECURE;
const VAPID_PUBLIC_KEY = process.env.VAPID_PUBLIC_KEY;
const VAPID_PRIVATE_KEY = process.env.VAPID_PRIVATE_KEY;
const VAPID_SUBJECT = process.env.VAPID_SUBJECT;
const OIDC_CLIENT_ID = process.env.OIDC_CLIENT_ID;
const OIDC_ISSUER_EXTERNAL_URL = process.env.OIDC_ISSUER_EXTERNAL_URL;
const OIDC_ISSUER_INTERNAL_URL = process.env.OIDC_ISSUER_INTERNAL_URL;

export {
  NODE_ENV,
  PORT,
  HOST_NAME,
  DB_HOSTNAME,
  DB_PORT,
  DB_TYPE,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  TYPEORM_SYNC,
  JWT_SECRET,
  EXPIRES_IN,
  SWAGGER,
  APP_NAME,
  APP_ENV,
  APP_DEBUG,
  APP_URL,
  APP_PORT,
  APP_URL_PREFIX,
  LOG_CHANNEL,
  DB_CONNECTION,
  DB_HOST,
  DB_DATABASE,
  TYPEORM_KEEPCONNECTIONALIVE,
  TYPEORM_LOGGING,
  TYPEORM_SYNCHRONIZE,
  TYPEORM_UUID_EXTENSION,
  BROADCAST_DRIVER,
  CACHE_DRIVER,
  QUEUE_CONNECTION,
  SESSION_DRIVER,
  SESSION_LIFETIME,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  MAIL_MAILER,
  MAIL_HOST,
  MAIL_PORT,
  MAIL_USERNAME,
  MAIL_PASSWORD,
  MAIL_ENCRYPTION,
  MAIL_SECURE,
  MAIL_FROM_ADDRESS,
  MAIL_FROM_NAME,
  MAIL_TEMPLATE_DIR,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_DEFAULT_REGION,
  AWS_BUCKET,
  PUSHER_APP_ID,
  PUSHER_APP_KEY,
  PUSHER_APP_SECRET,
  PUSHER_APP_CLUSTER,
  MIX_PUSHER_APP_KEY,
  MIX_PUSHER_APP_CLUSTER,
  USER_PASSWORD_BCRYPT_SALT_ROUNDS,
  JWT_SIGN_OPTIONS_ALGORITHM,
  JWT_SIGN_OPTIONS_EXPIRESIN,
  SWAGGER_ENABLED,
  SWAGGER_PATH,
  IMAGE_PATH,
  IMAGE_API,
  IMAGE_FILE_SIZE,
  PRODUCT_TEMPLATES_PATH,
  BARCODE,
  TWILIO_NUMBER,
  TWILIO_SID,
  TWILIO_AUTH,
  PRINTER_API,
  UPLOAD_FILE_PATH,
  UPLOAD_FILE_SIZE,
  EXPIRE_TIME,
  EMAIL_SECURE,
  OIDC_ISSUER_INTERNAL_URL,
  VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY,
  VAPID_SUBJECT,
  OIDC_ISSUER_EXTERNAL_URL,
  OIDC_CLIENT_ID,
};
