name: 00.gke-deployment
on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string
      DOT_ENV_FILE_NAME:
        required: true
        type: string
      PORT:
        required: true
        type: string
    secrets:
      HARBOR_URL:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SERVER_IP:
        required: true
      SERVER_USER:
        required: true
      NODE_APP_DB_PASSWORD:
        required: true
      NODE_APP_DB_USERNAME:
        required: true
      NODE_APP_DB_HOSTNAME:
        required: true
      NODE_APP_DB_PORT:
        required: true

env:
  IMAGE: ${{ inputs.IMAGE }}
  DOT_ENV_FILE_NAME: ${{ inputs.DOT_ENV_FILE_NAME }}
  PORT: ${{ inputs.PORT }}
  HARBOR_URL: ${{ secrets.HARBOR_URL }}
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  NODE_APP_DB_PASSWORD: ${{ secrets.NODE_APP_DB_PASSWORD }}
  NODE_APP_DB_USERNAME: ${{ secrets.NODE_APP_DB_USERNAME }}
  NODE_APP_DB_HOSTNAME: ${{ secrets.NODE_APP_DB_HOSTNAME }}
  NODE_APP_DB_PORT: ${{ secrets.NODE_APP_DB_PORT }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare dotenv
        run: |
          rm -rf .env
          echo "NODE_APP_DB_USERNAME=$NODE_APP_DB_USERNAME" >> .env
          echo "NODE_APP_DB_PORT=$NODE_APP_DB_PORT" >> .env
          echo "NODE_APP_DB_PASSWORD=$NODE_APP_DB_PASSWORD" >> .env
          echo "NODE_APP_DB_HOSTNAME=$NODE_APP_DB_HOSTNAME" >> .env
          cat $DOT_ENV_FILE_NAME >> .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Log in to Harbor
        run: docker login $HARBOR_URL -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD"  

      - name: Deploy with Docker Compose
        run: docker compose push

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p 775 $SERVER_USER@$SERVER_IP "
            podman pull $HARBOR_URL/$HARBOR_USERNAME/$IMAGE:$GITHUB_SHA &&
            podman stop $IMAGE || true &&
            podman rm $IMAGE || true &&
            podman run -d \
              -v /home/primetek/resource-web/cdn:/home/ubuntu/cdn \
              -p ${PORT}:4000 \
              --name $IMAGE \
              $HARBOR_URL/$HARBOR_USERNAME/$IMAGE:$GITHUB_SHA"
              

# docker run -d \
#   --gpus all \
#   -e NVIDIA_DRIVER_CAPABILITIES=all \
#   -e CONNECTION_TIMEOUT=600000 \
#   -e DISPLAY=$DISPLAY \
#   -e CHROME_LAUNCH_ARGS="--headless=new --enable-webgl --ignore-gpu-blocklist --use-gl=egl --enable-gpu-compositing --enable-zero-copy --disable-software-rasterizer --disable-features=WebGPU --window-size=1920,1080" \
#   -v /tmp/.X11-unix:/tmp/.X11-unix \
#   -v /dev/dri:/dev/dri \
#   --device /dev/dri \
#   --shm-size=2gb \
#   -p 5011:3000 \
#   browserless/chrome:latest