name: 01.build-develop
on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  DEPLOYMENT_NAME: be-app-2024
  IMAGE: be-app-2024
  INGRESS_IP: 4.230.8.218
  DOT_ENV_FILE_NAME: .env.develop
jobs:
  variables:
    name: setup variable
    runs-on: ubuntu-latest
    outputs:
      DEPLOYMENT_NAME: ${{ env.DEPLOYMENT_NAME }}
      IMAGE: ${{ env.IMAGE }}
      INGRESS_IP: ${{ env.INGRESS_IP }}
      DOT_ENV_FILE_NAME: ${{ env.DOT_ENV_FILE_NAME }}
    steps:
      - name: Echo
        run: echo prepare variable
  be-app-2024:
    needs: variables
    name: deploy be-app-2024
    uses: ./.github/workflows/00.gke-deployment.yml
    with:
      DEPLOYMENT_NAME: ${{ needs.variables.outputs.DEPLOYMENT_NAME }}
      IMAGE: ${{ needs.variables.outputs.IMAGE }}
      INGRESS_IP: ${{ needs.variables.outputs.INGRESS_IP }}
      DOT_ENV_FILE_NAME: ${{ needs.variables.outputs.DOT_ENV_FILE_NAME }}