name: 01.build-develop
on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true

env:
  IMAGE: be-app
  DOT_ENV_FILE_NAME: .env.develop
jobs:
  variables:
    name: setup variable
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ env.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ env.DOT_ENV_FILE_NAME }}
    steps:
      - name: Echo
        run: echo prepare variable
  be-app:
    needs: variables
    name: deploy be-app
    uses: ./.github/workflows/00.gke-deployment.yml
    with:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      PASSWORD_DOCKER_HUB: ${{ secrets.PASSWORD_DOCKER_HUB }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      PORT: ${{ secrets.PORT }}