name: 01.develop
on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        default: 'OK'
        required: true
env:
  IMAGE: be-app
  DOT_ENV_FILE_NAME: .env.develop
  PORT: 4000
jobs:
  variables:
    name: setup variable
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ env.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ env.DOT_ENV_FILE_NAME }}
      PORT: ${{ env.PORT }}
    steps:
      - name: Echo
        run: echo prepare variable
  be-app:
    needs: variables
    name: deploy be-app
    uses: ./.github/workflows/00.gke-deployment.yml
    with:
      IMAGE: ${{ needs.variables.outputs.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ needs.variables.outputs.DOT_ENV_FILE_NAME }}
      PORT: ${{ needs.variables.outputs.PORT }}
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.PASSWORD_DOCKER_HUB }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      NODE_APP_OPENAI_API_KEY: ${{ secrets.NODE_APP_OPENAI_API_KEY }}