name: 01.deploy-database

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  SERVER_IP: "20.249.210.27"
  SERVER_USER: "outerxspace"
  IMAGE: be-app
  USERNAME_DOCKER_HUB: warjamma

jobs: 
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: e9de0229-e0fe-4361-b155-2139f1e2f85e
          tenant-id: 2dff09ac-2b3b-4182-9953-2b548e0d0b39
          subscription-id: 3a5db49d-c188-41c0-9759-c6f3794aa918
          enable-AzPSSession: true
      - name: Azure CLI script
        uses: azure/CLI@v1
        env:
          AZURE_CORE_OUTPUT: none
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Deploy
        run: |
            sudo docker-compose up -d