name: 01.deploy-develop

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  SERVER_IP: "4.230.8.218"
  SERVER_USER: "outerxspace"
  IMAGE: beapp2024
  USERNAME_DOCKER_HUB: warjamma

permissions:
  id-token: write
  contents: write
  issues: write
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            allow-no-subscriptions: true
      - name: Deploy
        run: |
          sudo docker pull $USERNAME_DOCKER_HUB/$IMAGE:latest
          sudo docker stop "$IMAGE" 2>/dev/null || true
          sudo docker rm "$IMAGE" 2>/dev/null || true         
          sudo docker run -d -p 8000:80 --name "$IMAGE" $USERNAME_DOCKER_HUB/$IMAGE:latest