name: 02.third-party-service
on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        default: 'OK'
        required: true
env:
  IMAGE: third-party-service
  DOT_ENV_FILE_NAME: .env.third-party-service
  PORT: 5002
jobs:
  variables:
    name: setup variable
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ env.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ env.DOT_ENV_FILE_NAME }}
      PORT: ${{ env.PORT }}
    steps:
      - name: Echo
        run: echo prepare variable
  third-party-service:
    needs: variables
    name: deploy third-party-service
    uses: ./.github/workflows/00.gke-deployment.yml
    with:
      IMAGE: ${{ needs.variables.outputs.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ needs.variables.outputs.DOT_ENV_FILE_NAME }}
      PORT: ${{ needs.variables.outputs.PORT }}
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.PASSWORD_DOCKER_HUB }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      NODE_APP_DB_PASSWORD: ${{ secrets.NODE_APP_DB_PASSWORD }}
      NODE_APP_DB_USERNAME: ${{ secrets.NODE_APP_DB_USERNAME }}
      NODE_APP_DB_HOSTNAME: ${{ secrets.NODE_APP_DB_HOSTNAME }}
      NODE_APP_DB_PORT: ${{ secrets.NODE_APP_DB_PORT }}